export interface BrawlerStats {
  id: string;
  name: string;
  role: string;
  hp: number;
  speed: number;
  regenRate: number;
  attackDamage: number;
  attackRange: number;
  attackCooldown: number;
  attackCharges: number;
  superCooldown: number;
  color: string;
  secondaryColor: string;
  accentColor: string;
  description: string;
  attackName: string;
  superName: string;
  attackDesc: string;
  superDesc: string;
  spriteRow: number;
  spriteCol: number;
}

export const BRAWLERS: BrawlerStats[] = [
  {
    id: "miya",
    name: "Мия",
    role: "Ассасин",
    hp: 3600,
    speed: 5.2,
    regenRate: 60,
    attackDamage: 400,
    attackRange: 220,
    attackCooldown: 1.2,
    attackCharges: 3,
    superCooldown: 20,
    color: "#7B2FBE",
    secondaryColor: "#4A0080",
    accentColor: "#FF1744",
    description: "Девушка-ниндзя с фиолетовыми волосами и двумя короткими мечами",
    attackName: "Теневые клинки",
    superName: "Разрыв реальности",
    attackDesc: "Бросает два сюрикена по дуге",
    superDesc: "Телепортируется за спину ближайшему врагу",
    spriteRow: 0,
    spriteCol: 0,
  },
  {
    id: "kibo",
    name: "Kibo",
    role: "Стрелок",
    hp: 3800,
    speed: 4.0,
    regenRate: 50,
    attackDamage: 320,
    attackRange: 550,
    attackCooldown: 1.0,
    attackCharges: 3,
    superCooldown: 25,
    color: "#1565C0",
    secondaryColor: "#FFFFFF",
    accentColor: "#40C4FF",
    description: "Парень в белом плаще со снайперской винтовкой и синими волосами",
    attackName: "Плазменная винтовка",
    superName: "Снайперский выстрел",
    attackDesc: "Мгновенный луч на 550px",
    superDesc: "Луч на всю карту, пронзает всех",
    spriteRow: 0,
    spriteCol: 1,
  },
  {
    id: "ronin",
    name: "Ronin",
    role: "Танк",
    hp: 5500,
    speed: 3.2,
    regenRate: 40,
    attackDamage: 300,
    attackRange: 160,
    attackCooldown: 1.4,
    attackCharges: 2,
    superCooldown: 22,
    color: "#B71C1C",
    secondaryColor: "#FFD700",
    accentColor: "#FF6F00",
    description: "Огромный самурай в красных доспехах с катаной",
    attackName: "Столб земли",
    superName: "Несокрушимая стена",
    attackDesc: "Конус 60°, урон всем врагам",
    superDesc: "Щит: -50% урона, отражение 30%",
    spriteRow: 0,
    spriteCol: 2,
  },
  {
    id: "yuki",
    name: "Yuki",
    role: "Поддержка",
    hp: 3200,
    speed: 4.2,
    regenRate: 70,
    attackDamage: 200,
    attackRange: 350,
    attackCooldown: 1.0,
    attackCharges: 3,
    superCooldown: 18,
    color: "#0288D1",
    secondaryColor: "#E1F5FE",
    accentColor: "#B2EBF2",
    description: "Девушка в синем кимоно с посохом и снежинкой",
    attackName: "Снежный шар",
    superName: "Исцеляющий снег",
    attackDesc: "Медленный шар с замедлением цели",
    superDesc: "Облако 140px: 300 ХП/сек союзникам",
    spriteRow: 0,
    spriteCol: 3,
  },
  {
    id: "kenji",
    name: "Kenji",
    role: "Контроллер",
    hp: 4000,
    speed: 3.8,
    regenRate: 55,
    attackDamage: 250,
    attackRange: 200,
    attackCooldown: 1.3,
    attackCharges: 2,
    superCooldown: 20,
    color: "#F9A825",
    secondaryColor: "#212121",
    accentColor: "#40C4FF",
    description: "Парень в жёлтом костюме с электрошокерами на руках",
    attackName: "Электрическая цепь",
    superName: "Клетка молний",
    attackDesc: "Молния прыгает до 3 врагов",
    superDesc: "Зона 110px: урон и замедление 5 сек",
    spriteRow: 0,
    spriteCol: 4,
  },
  {
    id: "hana",
    name: "Hana",
    role: "Хилер",
    hp: 3000,
    speed: 4.5,
    regenRate: 80,
    attackDamage: 150,
    attackRange: 400,
    attackCooldown: 0.9,
    attackCharges: 4,
    superCooldown: 16,
    color: "#E91E8C",
    secondaryColor: "#FCE4EC",
    accentColor: "#FF80AB",
    description: "Девушка в розовом медицинском халате с лечебным пистолетом",
    attackName: "Лечебная пуля",
    superName: "Цветущий сад",
    attackDesc: "Лечит союзников или наносит урон",
    superDesc: "Зона 160px: 200 ХП/сек союзникам",
    spriteRow: 1,
    spriteCol: 0,
  },
  {
    id: "goro",
    name: "Goro",
    role: "Берсерк",
    hp: 6200,
    speed: 2.9,
    regenRate: 35,
    attackDamage: 450,
    attackRange: 90,
    attackCooldown: 1.5,
    attackCharges: 2,
    superCooldown: 22,
    color: "#8D4E2B",
    secondaryColor: "#FF3D00",
    accentColor: "#BF360C",
    description: "Огромный бородатый мужчина с двумя боевыми топорами",
    attackName: "Двойной топор",
    superName: "Ярость берсерка",
    attackDesc: "Вращение 360°, дальность 90px",
    superDesc: "5 сек: +40% скорость, +50% урон",
    spriteRow: 1,
    spriteCol: 1,
  },
  {
    id: "sora",
    name: "Sora",
    role: "Маг",
    hp: 3400,
    speed: 4.0,
    regenRate: 45,
    attackDamage: 300,
    attackRange: 400,
    attackCooldown: 1.1,
    attackCharges: 3,
    superCooldown: 24,
    color: "#1A237E",
    secondaryColor: "#FFD700",
    accentColor: "#FF6F00",
    description: "Парень в синей мантии с летающей книгой заклинаний",
    attackName: "Огненный шар",
    superName: "Метеоритный дождь",
    attackDesc: "Шар взрывается при попадании",
    superDesc: "5 метеоров в области, 250 урона каждый",
    spriteRow: 1,
    spriteCol: 2,
  },
  {
    id: "rin",
    name: "Rin",
    role: "Отравитель",
    hp: 3300,
    speed: 5.0,
    regenRate: 50,
    attackDamage: 350,
    attackRange: 300,
    attackCooldown: 1.0,
    attackCharges: 3,
    superCooldown: 19,
    color: "#2E7D32",
    secondaryColor: "#8BC34A",
    accentColor: "#CE93D8",
    description: "Девушка с зелёными волосами и ядовитыми кинжалами",
    attackName: "Отравленный кинжал",
    superName: "Облако яда",
    attackDesc: "Нож + яд 100 урона/сек 3 сек",
    superDesc: "Облако 100px: 150 урона/сек 4 сек",
    spriteRow: 1,
    spriteCol: 3,
  },
  {
    id: "taro",
    name: "Taro",
    role: "Инженер",
    hp: 3700,
    speed: 3.5,
    regenRate: 40,
    attackDamage: 400,
    attackRange: 80,
    attackCooldown: 0.8,
    attackCharges: 3,
    superCooldown: 25,
    color: "#5D4037",
    secondaryColor: "#CD9B39",
    accentColor: "#78909C",
    description: "Старик с гаечным ключом и механическим рюкзаком",
    attackName: "Гаечный ключ",
    superName: "Турель",
    attackDesc: "Ближний бой 80px, урон 400",
    superDesc: "Ставит турель: 200 ХП, 150 урона",
    spriteRow: 1,
    spriteCol: 4,
  },
];

export function getBrawlerById(id: string): BrawlerStats | undefined {
  return BRAWLERS.find((b) => b.id === id);
}

export function getScaledStats(brawler: BrawlerStats, level: number) {
  const lvl = Math.max(1, Math.min(10, level));
  return {
    hp: Math.floor(brawler.hp * (1 + 0.05 * (lvl - 1))),
    attackDamage: Math.floor(brawler.attackDamage * (1 + 0.03 * (lvl - 1))),
    speed: brawler.speed,
    regenRate: brawler.regenRate,
    attackCooldown: brawler.attackCooldown,
    attackCharges: brawler.attackCharges,
    attackRange: brawler.attackRange,
  };
}
